/**
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.15
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NamSorApiV2) {
      root.NamSorApiV2 = {};
    }
    root.NamSorApiV2.APIKeyOut = factory(root.NamSorApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The APIKeyOut model module.
   * @module model/APIKeyOut
   * @version 2.0.15
   */

  /**
   * Constructs a new <code>APIKeyOut</code>.
   * The API Key.
   * @alias module:model/APIKeyOut
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>APIKeyOut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIKeyOut} obj Optional instance to populate.
   * @return {module:model/APIKeyOut} The populated <code>APIKeyOut</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('apiKey')) {
        obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('admin')) {
        obj['admin'] = ApiClient.convertToType(data['admin'], 'Boolean');
      }
      if (data.hasOwnProperty('vetted')) {
        obj['vetted'] = ApiClient.convertToType(data['vetted'], 'Boolean');
      }
      if (data.hasOwnProperty('learnable')) {
        obj['learnable'] = ApiClient.convertToType(data['learnable'], 'Boolean');
      }
      if (data.hasOwnProperty('anonymized')) {
        obj['anonymized'] = ApiClient.convertToType(data['anonymized'], 'Boolean');
      }
      if (data.hasOwnProperty('partner')) {
        obj['partner'] = ApiClient.convertToType(data['partner'], 'Boolean');
      }
      if (data.hasOwnProperty('striped')) {
        obj['striped'] = ApiClient.convertToType(data['striped'], 'Boolean');
      }
      if (data.hasOwnProperty('corporate')) {
        obj['corporate'] = ApiClient.convertToType(data['corporate'], 'Boolean');
      }
      if (data.hasOwnProperty('disabled')) {
        obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * The user API Key.
   * @member {String} apiKey
   */
  exports.prototype['apiKey'] = undefined;
  /**
   * The user identifier.
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * The API Key has admin role.
   * @member {Boolean} admin
   */
  exports.prototype['admin'] = undefined;
  /**
   * The API Key is vetted (assumed truthful) for machine learning.
   * @member {Boolean} vetted
   */
  exports.prototype['vetted'] = undefined;
  /**
   * The API Key is learnable (without assuming truthfulness) for machine learning. Set learnable=false and anonymized=true for highest privacy (ie. to forget data as it's processed).
   * @member {Boolean} learnable
   */
  exports.prototype['learnable'] = undefined;
  /**
   * The API Key is anonymized (using SHA-252 digest for logging). Set learnable=false and anonymized=true for highest privacy (ie. to forget data as it's processed).
   * @member {Boolean} anonymized
   */
  exports.prototype['anonymized'] = undefined;
  /**
   * The API Key has partner role.
   * @member {Boolean} partner
   */
  exports.prototype['partner'] = undefined;
  /**
   * The API Key is associated to a valid Stripe account.
   * @member {Boolean} striped
   */
  exports.prototype['striped'] = undefined;
  /**
   * The API Key has role corporate (ex SWIFT payments instead of Stripe payments).
   * @member {Boolean} corporate
   */
  exports.prototype['corporate'] = undefined;
  /**
   * The API Key is temporarily or permanently disabled.
   * @member {Boolean} disabled
   */
  exports.prototype['disabled'] = undefined;



  return exports;
}));


