/**
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.15
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NamSorApiV2) {
      root.NamSorApiV2 = {};
    }
    root.NamSorApiV2.APIPlanSubscriptionOut = factory(root.NamSorApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The APIPlanSubscriptionOut model module.
   * @module model/APIPlanSubscriptionOut
   * @version 2.0.15
   */

  /**
   * Constructs a new <code>APIPlanSubscriptionOut</code>.
   * The API Plan governing the subscription.
   * @alias module:model/APIPlanSubscriptionOut
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>APIPlanSubscriptionOut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIPlanSubscriptionOut} obj Optional instance to populate.
   * @return {module:model/APIPlanSubscriptionOut} The populated <code>APIPlanSubscriptionOut</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('apiKey')) {
        obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
      }
      if (data.hasOwnProperty('planStarted')) {
        obj['planStarted'] = ApiClient.convertToType(data['planStarted'], 'Number');
      }
      if (data.hasOwnProperty('priorPlanStarted')) {
        obj['priorPlanStarted'] = ApiClient.convertToType(data['priorPlanStarted'], 'Number');
      }
      if (data.hasOwnProperty('planEnded')) {
        obj['planEnded'] = ApiClient.convertToType(data['planEnded'], 'Number');
      }
      if (data.hasOwnProperty('taxRate')) {
        obj['taxRate'] = ApiClient.convertToType(data['taxRate'], 'Number');
      }
      if (data.hasOwnProperty('planName')) {
        obj['planName'] = ApiClient.convertToType(data['planName'], 'String');
      }
      if (data.hasOwnProperty('planBaseFeesKey')) {
        obj['planBaseFeesKey'] = ApiClient.convertToType(data['planBaseFeesKey'], 'String');
      }
      if (data.hasOwnProperty('planStatus')) {
        obj['planStatus'] = ApiClient.convertToType(data['planStatus'], 'String');
      }
      if (data.hasOwnProperty('planQuota')) {
        obj['planQuota'] = ApiClient.convertToType(data['planQuota'], 'Number');
      }
      if (data.hasOwnProperty('priceUSD')) {
        obj['priceUSD'] = ApiClient.convertToType(data['priceUSD'], 'Number');
      }
      if (data.hasOwnProperty('priceOverageUSD')) {
        obj['priceOverageUSD'] = ApiClient.convertToType(data['priceOverageUSD'], 'Number');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('priceOverage')) {
        obj['priceOverage'] = ApiClient.convertToType(data['priceOverage'], 'Number');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('currencyFactor')) {
        obj['currencyFactor'] = ApiClient.convertToType(data['currencyFactor'], 'Number');
      }
      if (data.hasOwnProperty('stripeCustomerId')) {
        obj['stripeCustomerId'] = ApiClient.convertToType(data['stripeCustomerId'], 'String');
      }
      if (data.hasOwnProperty('stripeStatus')) {
        obj['stripeStatus'] = ApiClient.convertToType(data['stripeStatus'], 'String');
      }
      if (data.hasOwnProperty('stripeSubscription')) {
        obj['stripeSubscription'] = ApiClient.convertToType(data['stripeSubscription'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
    }
    return obj;
  }

  /**
   * User API Key.
   * @member {String} apiKey
   */
  exports.prototype['apiKey'] = undefined;
  /**
   * Datetime when the user subscribed to the current plan.
   * @member {Number} planStarted
   */
  exports.prototype['planStarted'] = undefined;
  /**
   * Datetime when the user subscribed to the prior plan.
   * @member {Number} priorPlanStarted
   */
  exports.prototype['priorPlanStarted'] = undefined;
  /**
   * Datetime when the user ended the plan.
   * @member {Number} planEnded
   */
  exports.prototype['planEnded'] = undefined;
  /**
   * Applicable tax rate for the plan.
   * @member {Number} taxRate
   */
  exports.prototype['taxRate'] = undefined;
  /**
   * Current plan name.
   * @member {String} planName
   */
  exports.prototype['planName'] = undefined;
  /**
   * Current plan key (as in Stripe product).
   * @member {String} planBaseFeesKey
   */
  exports.prototype['planBaseFeesKey'] = undefined;
  /**
   * Plan status.
   * @member {String} planStatus
   */
  exports.prototype['planStatus'] = undefined;
  /**
   * Current plan quota in quantity of units (NB: some API use several units per name).
   * @member {Number} planQuota
   */
  exports.prototype['planQuota'] = undefined;
  /**
   * Current plan monthly price expressed in USD (includes a free quota).
   * @member {Number} priceUSD
   */
  exports.prototype['priceUSD'] = undefined;
  /**
   * Current plan price for overages expressed in USD (extra price per unit above the free quota).
   * @member {Number} priceOverageUSD
   */
  exports.prototype['priceOverageUSD'] = undefined;
  /**
   * Current plan price for overages expressed in Currency (extra price per unit above the free quota).
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * Current plan price for overages expressed in Currency (extra price per unit above the free quota).
   * @member {Number} priceOverage
   */
  exports.prototype['priceOverage'] = undefined;
  /**
   * Current plan Currency for prices.
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * For USD, GBP, EUR - the factor is 1.
   * @member {Number} currencyFactor
   */
  exports.prototype['currencyFactor'] = undefined;
  /**
   * Stripe customer identifier.
   * @member {String} stripeCustomerId
   */
  exports.prototype['stripeCustomerId'] = undefined;
  /**
   * Stripe status ex active.
   * @member {String} stripeStatus
   */
  exports.prototype['stripeStatus'] = undefined;
  /**
   * Stripe subscription identifier.
   * @member {String} stripeSubscription
   */
  exports.prototype['stripeSubscription'] = undefined;
  /**
   * Internal user identifier.
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;



  return exports;
}));


