/**
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.15
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NamSorApiV2) {
      root.NamSorApiV2 = {};
    }
    root.NamSorApiV2.APIUsageAggregatedOut = factory(root.NamSorApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The APIUsageAggregatedOut model module.
   * @module model/APIUsageAggregatedOut
   * @version 2.0.15
   */

  /**
   * Constructs a new <code>APIUsageAggregatedOut</code>.
   * @alias module:model/APIUsageAggregatedOut
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>APIUsageAggregatedOut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/APIUsageAggregatedOut} obj Optional instance to populate.
   * @return {module:model/APIUsageAggregatedOut} The populated <code>APIUsageAggregatedOut</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('timeUnit')) {
        obj['timeUnit'] = ApiClient.convertToType(data['timeUnit'], 'String');
      }
      if (data.hasOwnProperty('periodStart')) {
        obj['periodStart'] = ApiClient.convertToType(data['periodStart'], 'Number');
      }
      if (data.hasOwnProperty('periodEnd')) {
        obj['periodEnd'] = ApiClient.convertToType(data['periodEnd'], 'Number');
      }
      if (data.hasOwnProperty('totalUsage')) {
        obj['totalUsage'] = ApiClient.convertToType(data['totalUsage'], 'Number');
      }
      if (data.hasOwnProperty('historyTruncated')) {
        obj['historyTruncated'] = ApiClient.convertToType(data['historyTruncated'], 'Boolean');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [['Number']]);
      }
      if (data.hasOwnProperty('colHeaders')) {
        obj['colHeaders'] = ApiClient.convertToType(data['colHeaders'], ['String']);
      }
      if (data.hasOwnProperty('rowHeaders')) {
        obj['rowHeaders'] = ApiClient.convertToType(data['rowHeaders'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Time unit is DAY, WEEK or MONTH depending on prior usage
   * @member {String} timeUnit
   */
  exports.prototype['timeUnit'] = undefined;
  /**
   * Start datetime of the reporting period
   * @member {Number} periodStart
   */
  exports.prototype['periodStart'] = undefined;
  /**
   * End datetime of the reporting period
   * @member {Number} periodEnd
   */
  exports.prototype['periodEnd'] = undefined;
  /**
   * Total usage in the current period
   * @member {Number} totalUsage
   */
  exports.prototype['totalUsage'] = undefined;
  /**
   * If the history was truncaded due to data limit
   * @member {Boolean} historyTruncated
   */
  exports.prototype['historyTruncated'] = undefined;
  /**
   * Data points : usage per DAY, WEEK or MONTH and per apiService
   * @member {Array.<Array.<Number>>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * apiServices as column headers 
   * @member {Array.<String>} colHeaders
   */
  exports.prototype['colHeaders'] = undefined;
  /**
   * dates as row headers 
   * @member {Array.<String>} rowHeaders
   */
  exports.prototype['rowHeaders'] = undefined;



  return exports;
}));


