/**
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.15
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NameMatchCandidateOut'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NameMatchCandidateOut'));
  } else {
    // Browser globals (root is window)
    if (!root.NamSorApiV2) {
      root.NamSorApiV2 = {};
    }
    root.NamSorApiV2.NameMatchCandidatesOut = factory(root.NamSorApiV2.ApiClient, root.NamSorApiV2.NameMatchCandidateOut);
  }
}(this, function(ApiClient, NameMatchCandidateOut) {
  'use strict';



  /**
   * The NameMatchCandidatesOut model module.
   * @module model/NameMatchCandidatesOut
   * @version 2.0.15
   */

  /**
   * Constructs a new <code>NameMatchCandidatesOut</code>.
   * Classified matched names
   * @alias module:model/NameMatchCandidatesOut
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>NameMatchCandidatesOut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NameMatchCandidatesOut} obj Optional instance to populate.
   * @return {module:model/NameMatchCandidatesOut} The populated <code>NameMatchCandidatesOut</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('script')) {
        obj['script'] = ApiClient.convertToType(data['script'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('firstName')) {
        obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
      }
      if (data.hasOwnProperty('lastName')) {
        obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
      }
      if (data.hasOwnProperty('orderOption')) {
        obj['orderOption'] = ApiClient.convertToType(data['orderOption'], 'String');
      }
      if (data.hasOwnProperty('matchCandidates')) {
        obj['matchCandidates'] = ApiClient.convertToType(data['matchCandidates'], [NameMatchCandidateOut]);
      }
    }
    return obj;
  }

  /**
   * @member {String} script
   */
  exports.prototype['script'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The first name (also known as given name)
   * @member {String} firstName
   */
  exports.prototype['firstName'] = undefined;
  /**
   * The last name (also known as family name, or surname)
   * @member {String} lastName
   */
  exports.prototype['lastName'] = undefined;
  /**
   * The option for ordering
   * @member {String} orderOption
   */
  exports.prototype['orderOption'] = undefined;
  /**
   * The ordered list of name matching candidates
   * @member {Array.<module:model/NameMatchCandidateOut>} matchCandidates
   */
  exports.prototype['matchCandidates'] = undefined;



  return exports;
}));


