/**
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.11
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.namsor.sdk2.invoke/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NamSorApiV2) {
      root.NamSorApiV2 = {};
    }
    root.NamSorApiV2.FirstLastNameOriginedOut = factory(root.NamSorApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The FirstLastNameOriginedOut model module.
   * @module com.namsor.sdk2.invoke/com.namsor.sdk2.model/FirstLastNameOriginedOut
   * @version 2.0.11
   */

  /**
   * Constructs a new <code>FirstLastNameOriginedOut</code>.
   * Represents the output of inferring the LIKELY country of Origin from a personal name.
   * @alias module:com.namsor.sdk2.invoke/com.namsor.sdk2.model/FirstLastNameOriginedOut
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>FirstLastNameOriginedOut</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.namsor.sdk2.invoke/com.namsor.sdk2.model/FirstLastNameOriginedOut} obj Optional instance to populate.
   * @return {module:com.namsor.sdk2.invoke/com.namsor.sdk2.model/FirstLastNameOriginedOut} The populated <code>FirstLastNameOriginedOut</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('firstName')) {
        obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
      }
      if (data.hasOwnProperty('lastName')) {
        obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
      }
      if (data.hasOwnProperty('countryOrigin')) {
        obj['countryOrigin'] = ApiClient.convertToType(data['countryOrigin'], 'String');
      }
      if (data.hasOwnProperty('countryOriginAlt')) {
        obj['countryOriginAlt'] = ApiClient.convertToType(data['countryOriginAlt'], 'String');
      }
      if (data.hasOwnProperty('countriesOriginTop')) {
        obj['countriesOriginTop'] = ApiClient.convertToType(data['countriesOriginTop'], ['String']);
      }
      if (data.hasOwnProperty('score')) {
        obj['score'] = ApiClient.convertToType(data['score'], 'Number');
      }
      if (data.hasOwnProperty('regionOrigin')) {
        obj['regionOrigin'] = ApiClient.convertToType(data['regionOrigin'], 'String');
      }
      if (data.hasOwnProperty('topRegionOrigin')) {
        obj['topRegionOrigin'] = ApiClient.convertToType(data['topRegionOrigin'], 'String');
      }
      if (data.hasOwnProperty('subRegionOrigin')) {
        obj['subRegionOrigin'] = ApiClient.convertToType(data['subRegionOrigin'], 'String');
      }
      if (data.hasOwnProperty('probabilityCalibrated')) {
        obj['probabilityCalibrated'] = ApiClient.convertToType(data['probabilityCalibrated'], 'Number');
      }
      if (data.hasOwnProperty('probabilityAltCalibrated')) {
        obj['probabilityAltCalibrated'] = ApiClient.convertToType(data['probabilityAltCalibrated'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} firstName
   */
  exports.prototype['firstName'] = undefined;
  /**
   * @member {String} lastName
   */
  exports.prototype['lastName'] = undefined;
  /**
   * Most likely country of Origin
   * @member {String} countryOrigin
   */
  exports.prototype['countryOrigin'] = undefined;
  /**
   * Second best alternative : country of Origin
   * @member {String} countryOriginAlt
   */
  exports.prototype['countryOriginAlt'] = undefined;
  /**
   * List countries of Origin (top 10)
   * @member {Array.<String>} countriesOriginTop
   */
  exports.prototype['countriesOriginTop'] = undefined;
  /**
   * Compatibility to NamSor_v1 Origin score value
   * @member {Number} score
   */
  exports.prototype['score'] = undefined;
  /**
   * Most likely region of Origin (based on countryOrigin ISO2 code)
   * @member {String} regionOrigin
   */
  exports.prototype['regionOrigin'] = undefined;
  /**
   * Most likely region of Origin (based on countryOrigin ISO2 code)
   * @member {String} topRegionOrigin
   */
  exports.prototype['topRegionOrigin'] = undefined;
  /**
   * Most likely region of Origin (based on countryOrigin ISO2 code)
   * @member {String} subRegionOrigin
   */
  exports.prototype['subRegionOrigin'] = undefined;
  /**
   * @member {Number} probabilityCalibrated
   */
  exports.prototype['probabilityCalibrated'] = undefined;
  /**
   * @member {Number} probabilityAltCalibrated
   */
  exports.prototype['probabilityAltCalibrated'] = undefined;



  return exports;
}));


