/**
 * NamSor API v2
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * OpenAPI spec version: 2.0.13
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NamSorApiV2);
  }
}(this, function(expect, NamSorApiV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NamSorApiV2.StripeCardOut();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StripeCardOut', function() {
    it('should create an instance of StripeCardOut', function() {
      // uncomment below and update the code to test StripeCardOut
      //var instance = new NamSorApiV2.StripeCardOut();
      //expect(instance).to.be.a(NamSorApiV2.StripeCardOut);
    });

    it('should have the property defaultCard (base name: "defaultCard")', function() {
      // uncomment below and update the code to test the property defaultCard
      //var instance = new NamSorApiV2.StripeCardOut();
      //expect(instance).to.be();
    });

    it('should have the property sourceId (base name: "sourceId")', function() {
      // uncomment below and update the code to test the property sourceId
      //var instance = new NamSorApiV2.StripeCardOut();
      //expect(instance).to.be();
    });

    it('should have the property expMonth (base name: "expMonth")', function() {
      // uncomment below and update the code to test the property expMonth
      //var instance = new NamSorApiV2.StripeCardOut();
      //expect(instance).to.be();
    });

    it('should have the property expYear (base name: "expYear")', function() {
      // uncomment below and update the code to test the property expYear
      //var instance = new NamSorApiV2.StripeCardOut();
      //expect(instance).to.be();
    });

    it('should have the property last4 (base name: "last4")', function() {
      // uncomment below and update the code to test the property last4
      //var instance = new NamSorApiV2.StripeCardOut();
      //expect(instance).to.be();
    });

    it('should have the property brand (base name: "brand")', function() {
      // uncomment below and update the code to test the property brand
      //var instance = new NamSorApiV2.StripeCardOut();
      //expect(instance).to.be();
    });

  });

}));
